[project]
name = "apiadapters"
version = "0.1.0"
description = "API adapters for services external and internal to D3"
readme = "README.md"
requires-python = ">=3.12, <4"
license = "GPL-3.0-or-later"
dependencies = [
  "cacheout>=0.16.0",
  "httpx>=0.28.1",
  "lxml>=5.3.2",
  "pandas>=2.3.2",
  "pydantic>=2.13.5",
  "tenacity>=9.1.2",
  "tinydb>=4.9.0",
  "xmlparser @ git+https://github.com/manuquadros/xmlparser.git@master",
]

[dependency-groups]
dev = [
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
  "pytest-cov>=7.1.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
